// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfessoresApi.Data;

#nullable disable

namespace ProfessoresApi.Migrations;

[DbContext(typeof(ProfessorContext))]
partial class ProfessorContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("ProfessoresApi.Models.Professor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<ulong>("CPF")
                    .HasColumnType("bigint unsigned");

                b.Property<string>("Disciplina")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Professores");
            });
#pragma warning restore 612, 618
    }
}
